//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace enti_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int ShoppingCartId { get; set; }
        public int CustomerId { get; set; }
        public string Message { get; set; }
        public bool IsCompleted { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
    }
}
